name: honbop_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.0
  hugeicons:
  get:
  google_maps_flutter: ^2.14.0
  # daum_postcode_search: ^1.0.0
  webview_flutter: ^4.8.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/address_search.html

  fonts:
   - family: Pretendard
     fonts:
       - asset: assets/fonts/Pretendard-Black.ttf
         weight: 900
       - asset: assets/fonts/Pretendard-Bold.ttf
         weight: 700
       - asset: assets/fonts/Pretendard-Medium.ttf
         weight: 400
